### ISSUE TITLE
Suggestion: leverage ansible_version

### ISSUE THREAD

**Issue by danvaida** [JonTheNiceGuy/ansible-version-check#2]
It's quite convenient when you have access to facts:
```bash
ok: [localhost] => {
    "msg": {
        "full": "2.6.0",
        "major": 2,
        "minor": 6,
        "revision": 0,
        "string": "2.6.0"
    }
}
```
For example:
```bash
      - assert:
        that:
          - "{{ ansible_version.major }} == 2"
          - "{{ ansible_version.minor }} == 6"
          - "{{ ansible_version.revision }} >= 0"
```

**Comment by JonTheNiceGuy** [comment]
That's a fair criticism. Unusually, running `ansible -m setup localhost | less` and searching for ansible_version doesn't show anything, but creating a playbook which references the ansible_version number like this works for at least ansible 2.3.

I need to take a look at this to get this change made, as I'm not currently using it "in anger" as the immediate requirement for the role vanished as everyone I was working with upgraded to ansible 2.5... but yes, I will get it sorted out.

**Comment by JonTheNiceGuy** [comment]
Hope the v1.0.1 release delivers this improvement!
